# Copyright (c) godot-rust; Bromeon and contributors.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: llvm
description: "Install LLVM + Clang, with caching"

inputs:
  llvm-version:
    required: false
    default: '15.0.7'
    description: "LLVM versions. Greater than 15 may not be supported in all runners."

runs:
  using: "composite"
  steps:
    # Replaces also backspaces on Windows, since they cause problems in Bash
    - name: "Set up install dir"
      run: |
        installDir=$(echo "${{ runner.temp }}/llvm" | sed "s!\\\\!/!")
        echo "LLVM_INSTALL_DIR=$installDir" >> $GITHUB_ENV
      shell: bash

    - name: "Cache LLVM and clang"
      id: cache-llvm
      # Note: conditionals not yet supported; see https://github.com/actions/runner/issues/834
      # if: inputs.llvm == 'true'
      uses: actions/cache@v3
      with:
#        path: |
#          C:/Program Files/LLVM
#          ./llvm
        path: ${{ env.LLVM_INSTALL_DIR }}
        key: "llvm-${{ inputs.llvm-version }}"

    - uses: KyleMayes/install-llvm-action@v1
      # if: inputs.llvm == 'true'
      with:
        # Newer versions failed on macOS with "Unsupported target! (platform='darwin', version='17.0.2')"
        version: "${{ inputs.llvm-version }}"
        directory: ${{ env.LLVM_INSTALL_DIR }}
        cached: ${{ steps.cache-llvm.outputs.cache-hit }}

    - name: "Print LLVM dir"
      #run: ls -ls $LLVM_DIR/lib
      run: |
        echo "LLVM_PATH: $LLVM_PATH"
      shell: bash