# Copyright (c) godot-rust; Bromeon and contributors.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# File format: see https://github.com/apache/skywalking-eyes/blob/main/test/testdata/.licenserc_language_config_test.yaml

header:
  license:
    spdx-id: 'MPL-2.0'
    # Note: There would be fields 'copyright-owner', 'copyright-year' and 'software-name', however these infos are not substituted into
    # the MPL-2.0 header, because the latter needs additional (external) copyright. Thus, content is overridden manually.
    content: |
      Copyright (c) godot-rust; Bromeon and contributors.
      This Source Code Form is subject to the terms of the Mozilla Public
      License, v. 2.0. If a copy of the MPL was not distributed with this
      file, You can obtain one at https://mozilla.org/MPL/2.0/.

  paths:
    - '**/*.rs'
    - '**/*.gd'
    - '**/*.sh'
    - '.github/**/*.yml'

#   paths-ignore:
#     - '...'

  comment: on-failure

  language:
    GDScript:
      extensions: ['.gd', '.sh']
      comment_style_id: 'Hashtag'
    Rust:
      extensions: ['.rs']
      comment_style_id: 'SlashAsterisk'
