/*
 * Copyright (c) godot-rust; Bromeon and contributors.
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

use proc_macro2::{Ident, Span, TokenStream};
use quote::{format_ident, quote, quote_spanned};

use crate::class::{
    into_signature_info, make_existence_check, make_method_registration, Field, FieldHint,
    FuncDefinition,
};
use crate::util::{make_funcs_collection_constant, KvParser};
use crate::{util, ParseResult};

/// Store info from `#[var]` attribute.
#[derive(Clone, Debug)]
pub struct FieldVar {
    /// What name this variable should have in Godot, if `None` then the Rust name should be used.
    pub rename: Option<Ident>,
    pub getter: GetterSetter,
    pub setter: GetterSetter,
    pub hint: FieldHint,
    pub usage_flags: UsageFlags,
    pub span: Span,
}

impl FieldVar {
    /// Parse a `#[var]` attribute to a `FieldVar` struct.
    ///
    /// Possible keys:
    /// - `rename = ident`
    /// - `get = expr`
    /// - `set = expr`
    /// - `hint = ident`
    /// - `hint_string = expr`
    /// - `usage_flags =
    pub(crate) fn new_from_kv(parser: &mut KvParser) -> ParseResult<Self> {
        let span = parser.span();
        let rename = parser.handle_ident("rename")?;
        let getter = GetterSetter::parse(parser, "get")?;
        let setter = GetterSetter::parse(parser, "set")?;

        let hint = parser.handle_ident("hint")?;

        let hint = if let Some(hint) = hint {
            let hint_string = parser.handle_expr("hint_string")?;

            FieldHint::new(hint, hint_string)
        } else {
            FieldHint::Inferred
        };

        let usage_flags = if let Some(mut parser) = parser.handle_array("usage_flags")? {
            let mut flags = Vec::new();

            while let Some(flag) = parser.next_ident()? {
                flags.push(flag)
            }

            parser.finish()?;

            UsageFlags::Custom(flags)
        } else {
            UsageFlags::Inferred
        };

        Ok(FieldVar {
            rename,
            getter,
            setter,
            hint,
            usage_flags,
            span,
        })
    }
}

impl Default for FieldVar {
    fn default() -> Self {
        Self {
            rename: Default::default(),
            getter: Default::default(),
            setter: Default::default(),
            hint: Default::default(),
            usage_flags: Default::default(),
            span: Span::call_site(),
        }
    }
}

#[derive(Default, Clone, Eq, PartialEq, Debug)]
pub enum GetterSetter {
    /// `#[var]`: Trivial getter/setter should be autogenerated.
    #[default]
    Generated,

    /// `#[var(get)]`: Custom setter with default name.
    Custom,

    /// `#[var(get = ident)]`: Custom setter with custom name.
    CustomRenamed(Ident),

    /// `#[var(no_get)]`: Getter/setter is absent, field is write/read only.
    Disabled,
}

impl GetterSetter {
    /// Parse a getter or setter from the attribute parser.
    pub(super) fn parse(parser: &mut KvParser, key: &str) -> ParseResult<Self> {
        // #[var(no_get)], #[var(no_set)]
        if parser.handle_alone(&format!("no_{key}"))? {
            return Ok(GetterSetter::Disabled);
        }

        let getter_setter = match parser.handle_any(key) {
            // No `get` key.
            None => GetterSetter::Generated,
            Some(value) => match value {
                // `get` without value: user-defined impl, but default name.
                None => GetterSetter::Custom,
                // `get = expr`
                Some(value) => GetterSetter::CustomRenamed(value.ident()?),
            },
        };

        Ok(getter_setter)
    }

    /// Returns the name, implementation, and export tokens for this `GetterSetter` declaration, for the
    /// given field and getter/setter kind.
    ///
    /// Returns `None` if no getter/setter should be created.
    pub(super) fn to_impl(
        &self,
        class_name: &Ident,
        kind: GetSet,
        field: &Field,
        rename: &Option<Ident>,
    ) -> Option<GetterSetterImpl> {
        match self {
            GetterSetter::Disabled => None,
            GetterSetter::Generated => Some(GetterSetterImpl::from_generated_impl(
                class_name, kind, field, rename,
            )),
            GetterSetter::Custom => Some(GetterSetterImpl::from_custom_impl(
                kind,
                &field.name,
                rename,
            )),
            GetterSetter::CustomRenamed(function_name) => {
                Some(GetterSetterImpl::from_custom_impl_renamed(function_name))
            }
        }
    }
}

/// Used to determine whether a [`GetterSetter`] is supposed to be a getter or setter.
#[derive(Copy, Clone, Eq, PartialEq, Debug)]
pub enum GetSet {
    Get,
    Set,
}

impl GetSet {
    // TODO(v0.5): migrate `rename` -> Option<String> and propagate upwards.
    pub fn make_fn_name(self, field_name: &Ident, rename: &Option<Ident>) -> Ident {
        let prefix = self.prefix();

        if let Some(rename) = rename {
            format_ident!("{prefix}{rename}", span = field_name.span())
        } else {
            format_ident!("{prefix}{field_name}", span = field_name.span())
        }
    }

    fn prefix(self) -> &'static str {
        match self {
            GetSet::Get => "get_",
            GetSet::Set => "set_",
        }
    }
}

#[derive(Clone, Debug)]
pub struct GetterSetterImpl {
    pub function_name: Ident,
    pub function_impl: TokenStream,
    pub export_token: TokenStream,
    pub funcs_collection_constant: TokenStream,
}

impl GetterSetterImpl {
    fn from_generated_impl(
        class_name: &Ident,
        kind: GetSet,
        field: &Field,
        rename: &Option<Ident>,
    ) -> Self {
        let Field {
            name: field_name,
            ty: field_type,
            ..
        } = field;

        // Function name gets field's span for IDE navigation (get_foo -> foo field).
        // Field type retains its original span for accurate type error locations.

        let function_name = kind.make_fn_name(field_name, rename);
        let field_span = field_name.span();

        let signature;
        let function_body;

        match kind {
            GetSet::Get => {
                // Use field's span so errors point to the field, not the derive macro.
                signature = quote_spanned! { field_span=>
                    fn #function_name(&self) -> <#field_type as ::godot::meta::GodotConvert>::Via
                };
                function_body = quote! {
                    <#field_type as ::godot::register::property::Var>::get_property(&self.#field_name)
                };
            }
            GetSet::Set => {
                // Use field's span so errors point to the field, not the derive macro.
                signature = quote_spanned! { field_span=>
                    fn #function_name(&mut self, #field_name: <#field_type as ::godot::meta::GodotConvert>::Via)
                };
                function_body = quote! {
                    <#field_type as ::godot::register::property::Var>::set_property(&mut self.#field_name, #field_name);
                };
            }
        }

        let function_impl = quote_spanned! { field_span=>
            pub #signature {
                #function_body
            }
        };

        let funcs_collection_constant =
            make_funcs_collection_constant(class_name, &function_name, None, &[]);

        let signature = util::parse_signature(signature);
        let export_token = make_method_registration(
            class_name,
            FuncDefinition {
                signature_info: into_signature_info(signature, class_name, false),
                // Since we're analyzing a struct's field, we don't have access to the corresponding get/set function's
                // external (non-#[func]) attributes. We have to assume the function exists and has the name the user
                // gave us, with the expected signature.
                // Ideally, we'd be able to place #[cfg_attr] on #[var(get)] and #[var(set)] to be able to match a
                // #[cfg()] (for instance) placed on the getter/setter function, but that is not currently supported.
                external_attributes: Vec::new(),
                registered_name: None,
                is_script_virtual: false,
                rpc_info: None,
            },
            None,
        );

        let export_token = export_token.expect("getter/setter generation should not fail");

        Self {
            function_name,
            function_impl,
            export_token,
            funcs_collection_constant,
        }
    }

    /// User-defined name.
    fn from_custom_impl_renamed(function_name: &Ident) -> Self {
        Self {
            function_name: function_name.clone(),
            function_impl: TokenStream::new(),
            export_token: make_existence_check(function_name),
            funcs_collection_constant: TokenStream::new(),
        }
    }

    /// Default name for property.
    fn from_custom_impl(kind: GetSet, field_name: &Ident, rename: &Option<Ident>) -> Self {
        let function_name = kind.make_fn_name(field_name, rename);
        let export_token = make_existence_check(&function_name);

        Self {
            function_name,
            function_impl: TokenStream::new(),
            export_token,
            funcs_collection_constant: TokenStream::new(),
        }
    }
}

#[derive(Default, Clone, Debug)]
pub enum UsageFlags {
    /// The usage flags should be inferred based on context.
    #[default]
    Inferred,

    /// The usage flags should be inferred based on context, such that they include export.
    InferredExport,

    /// Use a custom set of usage flags provided by the user.
    Custom(Vec<Ident>),
}

impl UsageFlags {
    pub fn is_inferred(&self) -> bool {
        matches!(self, Self::Inferred)
    }
}
